#!/bin/bash
# Run cc64 in VICE emulator with charset adapted for use with C 
# as generated by c-char-rom-gen, namely including the chars
# \^_{|}~ needed by C.

set -e

cc64="$1"
if test -z "$cc64"
then
  cc64="cc64v05"
fi

x64 \
  -virtualdev \
  +truedrive \
  -drive8type 1541 \
  -fs8 c64files \
  -chargen c-chargen \
  -symkeymap ./x11_sym_uf_de.vkm \
  -keymap 2 \
  -autostart "$cc64".T64 \
